【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

ab_11 = (-1*0) + (2*0) + (3*2)
ab_12 = (-1*2) + (2*2) + (3*9)
ab_13 = (-1*1) + (2*-8) + (3*-1)
ab_21 = (4*0) + (-5*0) + (6*2)
ab_22 = (4*2) + (-5*2) + (6*9)
ab_23 = (4*1) + (-5*-8) + (6*-1)
ab_31 = (7*0) + (8*0) + (-9*2)
ab_32 = (7*2) + (8*2) + (-9*9)
ab_33 = (7*1) + (8*-8) + (-9*-1)

ab_ndarray = np.array([[ab_11,ab_12,ab_13],[ab_21,ab_22,ab_23],[ab_31,ab_32,ab_33]])
print(ab_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。
これらを使い行列積を計算してください。

In [2]:
print("np.dot():", np.dot(a_ndarray, b_ndarray))
print("np.matmul()", np.matmul(a_ndarray, b_ndarray))
print("@", a_ndarray @ b_ndarray)

np.dot(): [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
np.matmul() [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
@ [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


【問題3】ある要素の計算を実装
この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [5]:
result = []
for i, j, k in a_ndarray:
    tmp = []
    for ii, jj, kk in zip(*b_ndarray):
        tmp.append(i * ii + j * jj + k * kk)
    result.append(tmp)
print("計算結果：",result)

計算結果： [[6, 29, -20], [12, 52, 38], [-18, -51, -48]]


【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。

In [6]:
def matrix(A,B):
    result = []
    for i, j, k in A:
        tmp = []
        for ii, jj, kk in zip(*B):
            tmp.append(i * ii + j * jj + k * kk)
        result.append(tmp)
    return result


【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。
if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [7]:
A = np.array([[-1, 2, 3], [4, -5, 6]])
B = np.array([[-9, 8, 7], [6, -5, 4]])

def matrix(A,B):
    result = []
    for i, j, k in A:
        tmp = []
        if len(B) < 3:
            print("計算するにはBの列数が足りてません")
            break
        else:
            for ii, jj, kk in zip(*B):
                tmp.append(i * ii + j * jj + k * kk)
        result.append(tmp)
    return result

print(matrix(A,B))

計算するにはBの列数が足りてません
[]


【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。
np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [8]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
e_ndarray = e_ndarray.T

print("計算結果：",np.matmul(d_ndarray,e_ndarray))

計算結果： [[ 46  -4]
 [-34  73]]
